version: "3.2"
services:
  web:
    build:
      context: ./compose/web/
      args:
        requirements: ../../requirements/production.txt
    networks:
      - default_network
      # - db_network
      # - nginx_network
    env_file:
      - env.production
    volumes:
      - .:/microservice/app
    #   - ./requirements/production.txt:/microservice/requirements.txt
    depends_on:
      - db
    expose:
      - 8080
    command: sh app-start.sh

  nginx:
    image: nginx
    build: ./compose/nginx

    env_file:
      - env.production

    volumes:
      - ./compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/usr/share/nginx/realestate/static
      - ./media:/usr/share/nginx/realestate/media

    networks:
      # - nginx_network
      - default_network
    depends_on:
      - web
    ports:
      - published: ${APP_PORT}
        target: 80
    # command: sh -c 'apt-get update && apt-get install -y vim less net-tools iputils-ping'

  db:
    # user: 1000:1000
    image: postgres:latest
    build:
      context: ./compose/db/

    env_file:
      - env.production

    restart: always
    # build:
    #   context: postgresql
    volumes:
      - type: bind
        source: ./backups/postgresql
        target: /backups
      - ./compose/db/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - default_network
    ports:
      - "5442:5432"
    expose:
      - "5432"

volumes:
  postgres_data:

networks:
  default_network:
