version: '3'

volumes:
  postgres-data:

services:
  web:
    container_name: "wr-web"
    build: ./
    working_dir: /code
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@db/wagtail
      # PYTHONPATH: /code/wagtail:/code/bakerydemo:$PYTHONPATH
    depends_on:
      - db

  db:
    container_name: "wr-db"
    image: postgres:12.3-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    expose:
      - "5432"
