# Generated by Django 3.1.13 on 2021-09-16 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Asset Type',
                'verbose_name_plural': 'Asset Types',
            },
        ),
        migrations.CreateModel(
            name='RealEstatePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RentalOfferContact',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Nouveau'), (2, 'Contacté'), (3, 'Archivé')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AddressPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('address_street', models.CharField(blank=True, max_length=256, null=True, verbose_name='Street')),
                ('address_city', models.CharField(blank=True, max_length=128, null=True, verbose_name='City')),
                ('address_zip', models.CharField(blank=True, max_length=32, null=True, verbose_name='Zip Code')),
                ('address_country', models.CharField(blank=True, max_length=64, null=True, verbose_name='Country')),
                ('address_website', models.URLField(blank=True, null=True, verbose_name='Web Site')),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='OfferIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'realestate.realestatepage'),
        ),
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Archived')], default=1)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='PropertyAssetIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='PropertyAssetPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('address_street', models.CharField(max_length=256, verbose_name='Street')),
                ('address_zip', models.CharField(max_length=32, verbose_name='Zip Code')),
                ('address_city', models.CharField(max_length=128, verbose_name='City')),
                ('address_country', models.CharField(default='France', max_length=64, verbose_name='Country')),
                ('asset_surface', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Surface')),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('asset_owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realestate.propertyassettype', verbose_name='Asset Type')),
            ],
            options={
                'verbose_name': 'Property Asset',
                'verbose_name_plural': 'Property Assets',
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='PropertyAssetTagIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='RealEstateHomePage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='RentalOfferContactIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='RentalOfferIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('tag', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tag')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='SaleOfferIndexPage',
            fields=[
                ('realestatepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.realestatepage')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('realestate.realestatepage',),
        ),
        migrations.CreateModel(
            name='PropertyAssetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'property asset categories',
            },
        ),
        migrations.CreateModel(
            name='AgencyPage',
            fields=[
                ('addresspage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.addresspage')),
                ('agency_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
            bases=('realestate.addresspage',),
        ),
        migrations.CreateModel(
            name='RentalOfferPage',
            fields=[
                ('offerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.offerpage')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Deposit')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Rental Offer',
                'verbose_name_plural': 'Rental Offers',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'realestate.offerpage'),
        ),
        migrations.CreateModel(
            name='SaleOfferPage',
            fields=[
                ('offerpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='realestate.offerpage')),
            ],
            options={
                'verbose_name': 'Sale Offer',
                'verbose_name_plural': 'Sale Offers',
            },
            bases=('realestate.offerpage',),
        ),
        migrations.CreateModel(
            name='PropertyAssetTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_propertyassettag_items', to='taggit.tag')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='realestate.propertyassetpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='propertyassetpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='realestate.PropertyAssetCategory'),
        ),
        migrations.AddField(
            model_name='propertyassetpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='realestate.PropertyAssetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='PageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='realestate.propertyassetpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleOfferPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_saleofferpagetag_items', to='taggit.tag')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='realestate.saleofferpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='saleofferpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='realestate.SaleOfferPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='RentalOfferPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_rentalofferpagetag_items', to='taggit.tag')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='realestate.rentalofferpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rentalofferpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='realestate.RentalOfferPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
