# Generated by Django 3.2.4 on 2021-06-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerpage',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='offerpage',
            name='asset',
        ),
    ]
