# Generated by Django 3.2.4 on 2021-06-30 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_auto_20210630_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerpage',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='propertyassetpage',
            name='short_description',
        ),
    ]
