# Generated by Django 3.1.13 on 2021-09-16 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('realestate', '0002_realestatehomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOfferContact',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Nouveau'), (2, 'Contacté'), (3, 'Archivé')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
