# Generated by Django 3.1.13 on 2021-09-16 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_rentaloffercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentaloffercontact',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
    ]
