# Generated by Django 3.2.5 on 2021-07-03 15:59

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('realestate', '0005_alter_offerpage_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='realestate.propertyassetpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_propertyassettag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PropertyAssetPageTag',
        ),
        migrations.AlterField(
            model_name='propertyassetpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='realestate.PropertyAssetTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
