# Generated by Django 3.2.5 on 2021-07-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_auto_20210703_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyassetcategory',
            options={'verbose_name_plural': 'property asset categories'},
        ),
    ]
