#!/bin/bash
set -e

DB_USER=wagestate
DB_NAME=wagestate
DB_PASSWORD=wagestate

# psql -h $POSTGRES_SERVICE -p $POSTGRES_PORT -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
# CREATE USER $DB_USER;
# EOSQL

psql -h $POSTGRES_SERVICE -p $POSTGRES_PORT -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE $DB_NAME;
ALTER ROLE $DB_NAME WITH PASSWORD '$DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOSQL

cat <<-EOSQL
    CREATE USER $DB_USER;
    CREATE DATABASE $DB_NAME;
ALTER ROLE $DB_NAME WITH PASSWORD '$DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOSQL
