# https://ahmedzbyr.gitlab.io/database/postgres-dockerfile/
FROM postgres:latest
EXPOSE 5432
# COPY init.db.sh /tmp/
# RUN rm /var/lib/postgresql/data/pg_hba.conf
# COPY pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
USER postgres
# RUN sleep 20;sh /tmp/init.db.sh
